version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASS}
      - TZ=Asia/Kathmandu
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}  # Keystore password
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: >
      bash -c "if [ ! -f /usr/share/opensearch/config/opensearch.keystore ]; then echo \"$KEYSTORE_PASSWORD\" | /usr/share/opensearch/bin/opensearch-keystore create; fi && /usr/share/opensearch/opensearch-docker-entrypoint.sh"
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "OPENSEARCH_HOSTS=[\"https://opensearch-node1:9200\"]"
      - TZ=Asia/Kathmandu
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    volumes:
      - "/home/saanx/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"
      - "/home/saanx/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro"
    ports:
      - "9090:9090"
      - "5140:5140/udp"
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
    driver: local

networks:
  opensearch-net:
